"""Employee_Role

Revision ID: 12190f59c541
Revises: 28a1d9f552bf
Create Date: 2026-06-01 14:18:31.121564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12190f59c541"
down_revision: Union[str, Sequence[str], None] = "28a1d9f552bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_ENUM = sa.Enum("UI", "UX", "Developer", "HR", name="employeerole")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "employees",
        sa.Column("role", _ROLE_ENUM, server_default="Developer", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    # ### end Alembic commands ###
