"""update employee schema fields and roles

Revision ID: 9ab9d0f19443
Revises: 12190f59c541
Create Date: 2026-06-10 15:33:40.708136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ab9d0f19443"
down_revision: Union[str, Sequence[str], None] = "12190f59c541"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_STATUS_ENUM = sa.Enum("Probation", "Active", "Inactive", name="employeestatus")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE employeerole ADD VALUE IF NOT EXISTS 'Manager'")
    _STATUS_ENUM.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "employees",
        sa.Column("status", _STATUS_ENUM, server_default="Active", nullable=True),
    )
    op.add_column(
        "employees", sa.Column("experience", sa.String(length=20), nullable=True)
    )
    op.add_column("employees", sa.Column("joining_date", sa.DateTime(), nullable=True))
    op.drop_column("employees", "age")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("employees", "joining_date")
    op.drop_column("employees", "experience")
    op.drop_column("employees", "status")
    _STATUS_ENUM.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
