"""unique_constrant_added

Revision ID: 9b0b68baa6fc
Revises: ceade6077b48
Create Date: 2026-05-28 23:03:58.339882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0b68baa6fc'
down_revision: Union[str, Sequence[str], None] = 'ceade6077b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departments', ['name'])
    op.drop_index(op.f('ix_employee_x_department_department_id'), table_name='employee_x_department')
    op.drop_index(op.f('ix_employee_x_department_employee_id'), table_name='employee_x_department')
    op.create_unique_constraint(None, 'employee_x_department', ['employee_id', 'department_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_x_department', type_='unique')
    op.create_index(op.f('ix_employee_x_department_employee_id'), 'employee_x_department', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_x_department_department_id'), 'employee_x_department', ['department_id'], unique=False)
    op.drop_constraint(None, 'departments', type_='unique')
    # ### end Alembic commands ###
